name: negociosapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  go_router: ^12.1.0
  get_it: ^7.6.4
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  freezed: ^2.4.5
  dio: ^5.3.3
  hive: ^2.2.3
  flutter_screenutil: ^5.9.0
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  flutter_native_splash: ^2.3.5
  equatable: ^2.0.5
  carousel_slider: ^4.2.1
  intl: ^0.18.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/linkedin.png
    - assets/marker.png
    - assets/logosplash.png
    - assets/img/
 

  fonts:
    - family:  ListingAppUI
      fonts:
        - asset: fonts/ListingAppUI.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-Black.ttf
          weight: 900
           
flutter_native_splash:
  color: "#042a49"
  image: assets/logosplash.png
  # branding: assets/logosplash.png
  # color_dark: "#121212"
  # image_dark: assets/logo-development.png
  # branding_dark: assets/branding-development.png

  android_12:
    
    
     
    # image_dark: assets/logo-development.png
    # icon_background_color_dark: "#121212"
